SELECT 
    cd.CALENDAR_DATE,
    cd.MONTH_NUMBER,
    cd.YEAR_NUMBER,
    cd.MONTH_YEAR_NAME,
    s.ID as SLIP_ID,
    s.NAME AS SLIP_NAME,
    s.MARINA_LOCATION_ID,
    ml.NAME as MARINA_LOCATION_NAME,
    r.ID as RESERVATION_ID,
    r.SCHEDULED_ARRIVAL_TIME,
    r.SCHEDULED_DEPARTURE_TIME,
    r.RESERVATION_STATUS_ID,
    rs.NAME as RESERVATION_STATUS_NAME,
    r.NAME as RESERVATION_NAME,
    CASE 
        WHEN r.ID IS NOT NULL AND r.RESERVATION_STATUS_ID IN (4, 6) THEN 1 
        ELSE 0 
    END as IS_OCCUPIED  -- 1 = occupied, 0 = vacant
FROM 
    CUSTOM_CALENDAR_DIMENSION cd
CROSS JOIN 
    DW_MOLO_SLIPS s
LEFT JOIN 
    DW_MOLO_RESERVATIONS r
    ON s.ID = r.SLIP_ID
    AND cd.CALENDAR_DATE >= TRUNC(r.SCHEDULED_ARRIVAL_TIME)
    AND cd.CALENDAR_DATE < TRUNC(r.SCHEDULED_DEPARTURE_TIME)
LEFT JOIN
    DW_MOLO_RESERVATION_STATUS rs ON r.RESERVATION_STATUS_ID = rs.ID
INNER JOIN
    DW_MOLO_MARINA_LOCATIONS ml ON s.MARINA_LOCATION_ID = ml.ID 
WHERE s.ACTIVE = 1 AND s.DO_NOT_COUNT_IN_OCCUPANCY IS NULL
ORDER BY 
    cd.CALENDAR_DATE, ml.ID, s.ID