SELECT 
    cd.CALENDAR_DATE,
    cd.MONTH_NUMBER,
    cd.YEAR_NUMBER,
    cd.MONTH_YEAR_NAME,
    r.id AS reservation_id, 
    r.NAME AS RESERVATION_NAME,
    rs.NAME AS RESERVATION_STATUS,
    rt.NAME AS RESERVATION_TYPE,
    sl.ID AS SLIP_ID,
    sl.NAME AS SLIP_NAME,
    ml.ID AS MARINA_LOCATION_ID,
    ml.NAME AS MARINA_LOCATION_NAME,
    -- Handling potential NULLs in SUBSTR/INSTR to prevent calculation errors
    CASE 
        WHEN INSTR(sl.RECOMMENDED_LOA, ':') > 0 
        THEN TO_NUMBER(SUBSTR(sl.RECOMMENDED_LOA, 1, INSTR(sl.RECOMMENDED_LOA, ':') - 1))
        ELSE 0 
    END AS LENGTH_IN_FT,
    r.SCHEDULED_ARRIVAL_TIME,
    r.SCHEDULED_DEPARTURE_TIME,
    -- Date difference for daily calculations
    NULLIF(TRUNC(r.SCHEDULED_DEPARTURE_TIME) - TRUNC(r.SCHEDULED_ARRIVAL_TIME), 0) AS RESERVATION_DAYS,
    ROUND(MONTHS_BETWEEN(r.SCHEDULED_DEPARTURE_TIME, r.SCHEDULED_ARRIVAL_TIME), 2) AS RESERVATION_MONTHS,
    r.RESERVATION_STATUS_ID,
    r.RATE AS reservation_rate,
    COALESCE(SUM(ii.total), 0) AS invoice_total,
    -- Calculations using CASE to avoid division by zero
    CASE 
        WHEN (TRUNC(r.SCHEDULED_DEPARTURE_TIME) - TRUNC(r.SCHEDULED_ARRIVAL_TIME)) > 0
        THEN ROUND(r.RATE / (TRUNC(r.SCHEDULED_DEPARTURE_TIME) - TRUNC(r.SCHEDULED_ARRIVAL_TIME)), 2)
        ELSE 0
    END AS reservation_daily_rate,
    CASE 
        WHEN (TRUNC(r.SCHEDULED_DEPARTURE_TIME) - TRUNC(r.SCHEDULED_ARRIVAL_TIME)) > 0
        THEN ROUND(COALESCE(SUM(ii.total), 0) / (TRUNC(r.SCHEDULED_DEPARTURE_TIME) - TRUNC(r.SCHEDULED_ARRIVAL_TIME)), 2)
        ELSE 0
    END AS invoice_daily_rate
FROM CUSTOM_CALENDAR_DIMENSION cd
-- JOIN 1: Ensure we only pull the month of October from the calendar dimension first
INNER JOIN DW_MOLO_RESERVATIONS r
    ON cd.CALENDAR_DATE >= TRUNC(r.SCHEDULED_ARRIVAL_TIME)
    AND cd.CALENDAR_DATE < TRUNC(r.SCHEDULED_DEPARTURE_TIME) + 1
LEFT JOIN DW_MOLO_RESERVATION_STATUS rs ON r.RESERVATION_STATUS_ID = rs.ID
LEFT JOIN DW_MOLO_RESERVATION_TYPES rt ON r.RESERVATION_TYPE_ID = rt.ID
LEFT JOIN DW_MOLO_SLIPS sl ON r.SLIP_ID = sl.ID
LEFT JOIN DW_MOLO_MARINA_LOCATIONS ml ON sl.MARINA_LOCATION_ID = ml.ID
LEFT JOIN DW_MOLO_INVOICES i ON r.id = i.reservation_id
LEFT JOIN DW_MOLO_INVOICE_ITEMS ii ON i.id = ii.invoice_id
    AND (ii.type_field = 'charge-reservation-seasonal' OR ii.type_field = 'charge-reservation-transitive')
    AND ii.is_void = 0 
    AND ii.status_field != 'deleted'
WHERE sl.ACTIVE = 1 
  AND sl.DO_NOT_COUNT_IN_OCCUPANCY IS NULL 
  AND r.RESERVATION_STATUS_ID IN (4)
GROUP BY 
    cd.CALENDAR_DATE, cd.MONTH_NUMBER, cd.YEAR_NUMBER, cd.MONTH_YEAR_NAME,
    r.id, r.NAME, rs.NAME, rt.NAME, sl.ID, sl.NAME, ml.ID, ml.NAME, 
    sl.RECOMMENDED_LOA, r.SCHEDULED_ARRIVAL_TIME, r.SCHEDULED_DEPARTURE_TIME, 
    r.RESERVATION_STATUS_ID, r.RATE
ORDER BY cd.CALENDAR_DATE, sl.ID