SELECT 
    cd.CALENDAR_DATE,
    cd.MONTH_NUMBER,
    cd.YEAR_NUMBER,
    cd.MONTH_YEAR_NAME,
    b.ID as BOAT_ID,
    b.NAME as BOAT_NAME,
    TO_NUMBER(SUBSTR(b.LOA, 1, INSTR(b.LOA, ':') - 1)) as BOAT_LOA_LENGTH,
    b.MAKE as BOAT_MAKE,
    b.MODEL as BOAT_MODEL,
    r.MARINA_LOCATION_ID,
    ml.NAME as MARINA_LOCATION_NAME,
    MAX(r.ID) as RESERVATION_ID,
    MAX(r.SCHEDULED_ARRIVAL_TIME) as SCHEDULED_ARRIVAL_TIME,
    MAX(r.SCHEDULED_DEPARTURE_TIME) as SCHEDULED_DEPARTURE_TIME,
    CASE 
        WHEN MAX(CASE WHEN r.RESERVATION_STATUS_ID = 4 THEN 1 ELSE 0 END) = 1 THEN 1 
        ELSE 0 
    END as OCCUPIES_SLIP
FROM 
    CUSTOM_CALENDAR_DIMENSION cd
LEFT JOIN 
    DW_MOLO_RESERVATIONS r
    ON cd.CALENDAR_DATE >= TRUNC(r.SCHEDULED_ARRIVAL_TIME)
    AND cd.CALENDAR_DATE < TRUNC(r.SCHEDULED_DEPARTURE_TIME)
LEFT JOIN
    DW_MOLO_BOATS b ON r.BOAT_ID = b.ID
LEFT JOIN
    DW_MOLO_MARINA_LOCATIONS ml ON r.MARINA_LOCATION_ID = ml.ID
GROUP BY 
    cd.CALENDAR_DATE,
    cd.MONTH_NUMBER,
    cd.YEAR_NUMBER,
    cd.MONTH_YEAR_NAME,
    b.ID,
    b.NAME,
    b.LOA,
    b.MAKE,
    b.MODEL,
    r.MARINA_LOCATION_ID,
    ml.NAME
ORDER BY 
    cd.CALENDAR_DATE, b.ID