
-- ============================================================================
-- Merge STG_STELLAR_STYLE_BOATS to DW_STELLAR_STYLE_BOATS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_STYLE_BOATS
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    MERGE INTO DW_STELLAR_STYLE_BOATS tgt
    USING STG_STELLAR_STYLE_BOATS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.STYLE_ID = src.STYLE_ID,
            tgt.BOAT_NUMBER = src.BOAT_NUMBER,
            tgt.PAPER_LESS_NUMBER = src.PAPER_LESS_NUMBER,
            tgt.MOTOR = src.MOTOR,
            tgt.MANUFACTURER = src.MANUFACTURER,
            tgt.SERIAL_NUMBER = src.SERIAL_NUMBER,
            tgt.IN_FLEET = src.IN_FLEET,
            tgt.HULL_NUMBER = src.HULL_NUMBER,
            tgt.STATE_NUMBER = src.STATE_NUMBER,
            tgt.CYLINDERS = src.CYLINDERS,
            tgt.HP = src.HP,
            tgt.MODEL = src.MODEL,
            tgt.BOAT_TYPE = src.BOAT_TYPE,
            tgt.PURCHASED_DATE = src.PURCHASED_DATE,
            tgt.PURCHASED_COST = src.PURCHASED_COST,
            tgt.SALE_DATE = src.SALE_DATE,
            tgt.SALE_PRICE = src.SALE_PRICE,
            tgt.CLUB_LOCATION = src.CLUB_LOCATION,
            tgt.DEALER_NAME = src.DEALER_NAME,
            tgt.DEALER_CITY = src.DEALER_CITY,
            tgt.DEALER_STATE = src.DEALER_STATE,
            tgt.PO_NUMBER = src.PO_NUMBER,
            tgt.BOAT_YEAR_MODEL = src.BOAT_YEAR_MODEL,
            tgt.MOTOR_YEAR_MODEL = src.MOTOR_YEAR_MODEL,
            tgt.MOTOR_MANUFACTURER_MODEL = src.MOTOR_MANUFACTURER_MODEL,
            tgt.STATE_REG_DATE = src.STATE_REG_DATE,
            tgt.STATE_REG_EXP_DATE = src.STATE_REG_EXP_DATE,
            tgt.ENGINE_PURCHASED_COST = src.ENGINE_PURCHASED_COST,
            tgt.BACKEND_DISPLAY = src.BACKEND_DISPLAY,
            tgt.POSITION_ORDER = src.POSITION_ORDER,
            tgt.STATUS_BOAT = src.STATUS_BOAT,
            tgt.SERVICE_START = src.SERVICE_START,
            tgt.SERVICE_END = src.SERVICE_END,
            tgt.CLEAN_STATUS = src.CLEAN_STATUS,
            tgt.INSURANCE_REG_NO = src.INSURANCE_REG_NO,
            tgt.BUOY_INSURANCE_STATUS = src.BUOY_INSURANCE_STATUS,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.STYLE_ID, -999) <> NVL(src.STYLE_ID, -999) OR
            NVL(tgt.BOAT_NUMBER, '~NULL~') <> NVL(src.BOAT_NUMBER, '~NULL~') OR
            NVL(tgt.PAPER_LESS_NUMBER, '~NULL~') <> NVL(src.PAPER_LESS_NUMBER, '~NULL~') OR
            NVL(tgt.MOTOR, '~NULL~') <> NVL(src.MOTOR, '~NULL~') OR
            NVL(tgt.MANUFACTURER, '~NULL~') <> NVL(src.MANUFACTURER, '~NULL~') OR
            NVL(tgt.SERIAL_NUMBER, '~NULL~') <> NVL(src.SERIAL_NUMBER, '~NULL~') OR
            NVL(tgt.IN_FLEET, '~NULL~') <> NVL(src.IN_FLEET, '~NULL~') OR
            NVL(tgt.HULL_NUMBER, '~NULL~') <> NVL(src.HULL_NUMBER, '~NULL~') OR
            NVL(tgt.STATE_NUMBER, '~NULL~') <> NVL(src.STATE_NUMBER, '~NULL~') OR
            NVL(tgt.CYLINDERS, '~NULL~') <> NVL(src.CYLINDERS, '~NULL~') OR
            NVL(tgt.HP, '~NULL~') <> NVL(src.HP, '~NULL~') OR
            NVL(tgt.MODEL, '~NULL~') <> NVL(src.MODEL, '~NULL~') OR
            NVL(tgt.BOAT_TYPE, '~NULL~') <> NVL(src.BOAT_TYPE, '~NULL~') OR
            NVL(tgt.PURCHASED_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.PURCHASED_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.PURCHASED_COST, -999.999) <> NVL(src.PURCHASED_COST, -999.999) OR
            NVL(tgt.SALE_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.SALE_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.SALE_PRICE, -999.999) <> NVL(src.SALE_PRICE, -999.999) OR
            NVL(tgt.CLUB_LOCATION, '~NULL~') <> NVL(src.CLUB_LOCATION, '~NULL~') OR
            NVL(tgt.DEALER_NAME, '~NULL~') <> NVL(src.DEALER_NAME, '~NULL~') OR
            NVL(tgt.DEALER_CITY, '~NULL~') <> NVL(src.DEALER_CITY, '~NULL~') OR
            NVL(tgt.DEALER_STATE, '~NULL~') <> NVL(src.DEALER_STATE, '~NULL~') OR
            NVL(tgt.PO_NUMBER, '~NULL~') <> NVL(src.PO_NUMBER, '~NULL~') OR
            NVL(tgt.BOAT_YEAR_MODEL, '~NULL~') <> NVL(src.BOAT_YEAR_MODEL, '~NULL~') OR
            NVL(tgt.MOTOR_YEAR_MODEL, '~NULL~') <> NVL(src.MOTOR_YEAR_MODEL, '~NULL~') OR
            NVL(tgt.MOTOR_MANUFACTURER_MODEL, '~NULL~') <> NVL(src.MOTOR_MANUFACTURER_MODEL, '~NULL~') OR
            NVL(tgt.STATE_REG_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.STATE_REG_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.STATE_REG_EXP_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.STATE_REG_EXP_DATE, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.ENGINE_PURCHASED_COST, -999.999) <> NVL(src.ENGINE_PURCHASED_COST, -999.999) OR
            NVL(tgt.BACKEND_DISPLAY, '~NULL~') <> NVL(src.BACKEND_DISPLAY, '~NULL~') OR
            NVL(tgt.POSITION_ORDER, -999) <> NVL(src.POSITION_ORDER, -999) OR
            NVL(tgt.STATUS_BOAT, '~NULL~') <> NVL(src.STATUS_BOAT, '~NULL~') OR
            NVL(tgt.SERVICE_START, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.SERVICE_START, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.SERVICE_END, TO_DATE('1900-01-01','YYYY-MM-DD')) <> NVL(src.SERVICE_END, TO_DATE('1900-01-01','YYYY-MM-DD')) OR
            NVL(tgt.CLEAN_STATUS, '~NULL~') <> NVL(src.CLEAN_STATUS, '~NULL~') OR
            NVL(tgt.INSURANCE_REG_NO, '~NULL~') <> NVL(src.INSURANCE_REG_NO, '~NULL~') OR
            NVL(tgt.BUOY_INSURANCE_STATUS, '~NULL~') <> NVL(src.BUOY_INSURANCE_STATUS, '~NULL~') OR
            NVL(tgt.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, STYLE_ID, BOAT_NUMBER, PAPER_LESS_NUMBER, MOTOR, MANUFACTURER, SERIAL_NUMBER, IN_FLEET, HULL_NUMBER, STATE_NUMBER, CYLINDERS, HP, MODEL, BOAT_TYPE, PURCHASED_DATE, PURCHASED_COST, SALE_DATE, SALE_PRICE, CLUB_LOCATION, DEALER_NAME, DEALER_CITY, DEALER_STATE, PO_NUMBER, BOAT_YEAR_MODEL, MOTOR_YEAR_MODEL, MOTOR_MANUFACTURER_MODEL, STATE_REG_DATE, STATE_REG_EXP_DATE, ENGINE_PURCHASED_COST, BACKEND_DISPLAY, POSITION_ORDER, STATUS_BOAT, SERVICE_START, SERVICE_END, CLEAN_STATUS, INSURANCE_REG_NO, BUOY_INSURANCE_STATUS, CREATED_AT, UPDATED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.STYLE_ID, src.BOAT_NUMBER, src.PAPER_LESS_NUMBER, src.MOTOR, src.MANUFACTURER, src.SERIAL_NUMBER, src.IN_FLEET, src.HULL_NUMBER, src.STATE_NUMBER, src.CYLINDERS, src.HP, src.MODEL, src.BOAT_TYPE, src.PURCHASED_DATE, src.PURCHASED_COST, src.SALE_DATE, src.SALE_PRICE, src.CLUB_LOCATION, src.DEALER_NAME, src.DEALER_CITY, src.DEALER_STATE, src.PO_NUMBER, src.BOAT_YEAR_MODEL, src.MOTOR_YEAR_MODEL, src.MOTOR_MANUFACTURER_MODEL, src.STATE_REG_DATE, src.STATE_REG_EXP_DATE, src.ENGINE_PURCHASED_COST, src.BACKEND_DISPLAY, src.POSITION_ORDER, src.STATUS_BOAT, src.SERVICE_START, src.SERVICE_END, src.CLEAN_STATUS, src.INSURANCE_REG_NO, src.BUOY_INSURANCE_STATUS, src.CREATED_AT, src.UPDATED_AT,
            v_timestamp,
            v_timestamp
        );
    
    SELECT COUNT(*) INTO v_inserted FROM DW_STELLAR_STYLE_BOATS WHERE DW_LAST_INSERTED = v_timestamp;
    SELECT COUNT(*) INTO v_updated FROM DW_STELLAR_STYLE_BOATS WHERE DW_LAST_UPDATED = v_timestamp AND DW_LAST_INSERTED < v_timestamp;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_STYLE_BOATS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_STYLE_BOATS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_STYLE_BOATS;
/
