
-- ============================================================================
-- Merge STG_STELLAR_BOOKING_BOATS to DW_STELLAR_BOOKING_BOATS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_STELLAR_BOOKING_BOATS
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    v_timestamp := SYSTIMESTAMP;
    
    MERGE INTO DW_STELLAR_BOOKING_BOATS tgt
    USING STG_STELLAR_BOOKING_BOATS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.BOOKING_ID = src.BOOKING_ID,
            tgt.STYLE_ID = src.STYLE_ID,
            tgt.BOAT_ID = src.BOAT_ID,
            tgt.TIME_ID = src.TIME_ID,
            tgt.TIMEFRAME_ID = src.TIMEFRAME_ID,
            tgt.MAIN_BOAT = src.MAIN_BOAT,
            tgt.NUM_PASSENGERS = src.NUM_PASSENGERS,
            tgt.BOAT_DEPARTURE = src.BOAT_DEPARTURE,
            tgt.BOAT_RETURN = src.BOAT_RETURN,
            tgt.STATUS_BOOKING = src.STATUS_BOOKING,
            tgt.PRICE = src.PRICE,
            tgt.PRICE_OVERRIDE = src.PRICE_OVERRIDE,
            tgt.SIGNATURE_DATE = src.SIGNATURE_DATE,
            tgt.CHECK_OUT_DATE = src.CHECK_OUT_DATE,
            tgt.CHECK_OUT_EQUIPMENT = src.CHECK_OUT_EQUIPMENT,
            tgt.CHECK_OUT_NOTES = src.CHECK_OUT_NOTES,
            tgt.CHECK_OUT_ENGINE_HOURS = src.CHECK_OUT_ENGINE_HOURS,
            tgt.CHECK_IN_DATE = src.CHECK_IN_DATE,
            tgt.CHECK_IN_EQUIPMENT = src.CHECK_IN_EQUIPMENT,
            tgt.CHECK_IN_NOTES = src.CHECK_IN_NOTES,
            tgt.CHECK_IN_ENGINE_HOURS = src.CHECK_IN_ENGINE_HOURS,
            tgt.CHECK_IN_HOURS = src.CHECK_IN_HOURS,
            tgt.CHECK_IN_DEPOSIT = src.CHECK_IN_DEPOSIT,
            tgt.CHECK_IN_WEATHER = src.CHECK_IN_WEATHER,
            tgt.CHECK_IN_LATE = src.CHECK_IN_LATE,
            tgt.CHECK_IN_MISC_NON_TAX = src.CHECK_IN_MISC_NON_TAX,
            tgt.CHECK_IN_MISC_TAX = src.CHECK_IN_MISC_TAX,
            tgt.CHECK_IN_CLEANING = src.CHECK_IN_CLEANING,
            tgt.CHECK_IN_GALLONS = src.CHECK_IN_GALLONS,
            tgt.CHECK_IN_FUEL = src.CHECK_IN_FUEL,
            tgt.CHECK_IN_DIESEL_GALLONS = src.CHECK_IN_DIESEL_GALLONS,
            tgt.CHECK_IN_DIESEL = src.CHECK_IN_DIESEL,
            tgt.CHECK_IN_TIP = src.CHECK_IN_TIP,
            tgt.CHECK_IN_TAX_1 = src.CHECK_IN_TAX_1,
            tgt.CHECK_IN_TAX_2 = src.CHECK_IN_TAX_2,
            tgt.CHECK_IN_TOTAL = src.CHECK_IN_TOTAL,
            tgt.QUEUE_ADMIN_ID = src.QUEUE_ADMIN_ID,
            tgt.QUEUE_DATE = src.QUEUE_DATE,
            tgt.ATTENDANT_QUEUE_ADMIN_ID = src.ATTENDANT_QUEUE_ADMIN_ID,
            tgt.ATTENDANT_WATER_ADMIN_ID = src.ATTENDANT_WATER_ADMIN_ID,
            tgt.BOAT_ASSIGNED = src.BOAT_ASSIGNED,
            tgt.ADDITIONAL_DRIVERS = src.ADDITIONAL_DRIVERS,
            tgt.ADDITIONAL_DRIVER_NAMES = src.ADDITIONAL_DRIVER_NAMES,
            tgt.ACCESSORIES_MIGRATED = src.ACCESSORIES_MIGRATED,
            tgt.PRICE_RULE_ID = src.PRICE_RULE_ID,
            tgt.PRICE_RULE_ORIGINAL_PRICE = src.PRICE_RULE_ORIGINAL_PRICE,
            tgt.PRICE_RULE_DYNAMIC_PRICE = src.PRICE_RULE_DYNAMIC_PRICE,
            tgt.PRICE_RULE_DIFFERENCE = src.PRICE_RULE_DIFFERENCE,
            tgt.EMERGENCY_NAME = src.EMERGENCY_NAME,
            tgt.EMERGENCY_PHONE = src.EMERGENCY_PHONE,
            tgt.DATE_OF_BIRTH = src.DATE_OF_BIRTH,
            tgt.CONTRACT_RETURN_PDF = src.CONTRACT_RETURN_PDF,
            tgt.CONTRACT_PDF = src.CONTRACT_PDF,
            tgt.CREATED_AT = src.CREATED_AT,
            tgt.UPDATED_AT = src.UPDATED_AT,
            tgt.DELETED_AT = src.DELETED_AT,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.BOOKING_ID, -999) <> NVL(src.BOOKING_ID, -999) OR
            NVL(tgt.STYLE_ID, -999) <> NVL(src.STYLE_ID, -999) OR
            NVL(tgt.BOAT_ID, '~NULL~') <> NVL(src.BOAT_ID, '~NULL~') OR
            NVL(tgt.TIME_ID, '~NULL~') <> NVL(src.TIME_ID, '~NULL~') OR
            NVL(tgt.TIMEFRAME_ID, -999) <> NVL(src.TIMEFRAME_ID, -999) OR
            NVL(tgt.MAIN_BOAT, -999) <> NVL(src.MAIN_BOAT, -999) OR
            NVL(tgt.NUM_PASSENGERS, -999) <> NVL(src.NUM_PASSENGERS, -999) OR
            NVL(tgt.BOAT_DEPARTURE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.BOAT_DEPARTURE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.BOAT_RETURN, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.BOAT_RETURN, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.STATUS_BOOKING, '~NULL~') <> NVL(src.STATUS_BOOKING, '~NULL~') OR
            NVL(tgt.PRICE, -999.999) <> NVL(src.PRICE, -999.999) OR
            NVL(tgt.PRICE_OVERRIDE, -999) <> NVL(src.PRICE_OVERRIDE, -999) OR
            NVL(tgt.SIGNATURE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.SIGNATURE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CHECK_OUT_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CHECK_OUT_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CHECK_OUT_ENGINE_HOURS, -999.999) <> NVL(src.CHECK_OUT_ENGINE_HOURS, -999.999) OR
            NVL(tgt.CHECK_IN_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CHECK_IN_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CHECK_IN_ENGINE_HOURS, -999.999) <> NVL(src.CHECK_IN_ENGINE_HOURS, -999.999) OR
            NVL(tgt.CHECK_IN_HOURS, -999.999) <> NVL(src.CHECK_IN_HOURS, -999.999) OR
            NVL(tgt.CHECK_IN_DEPOSIT, -999.999) <> NVL(src.CHECK_IN_DEPOSIT, -999.999) OR
            NVL(tgt.CHECK_IN_WEATHER, -999.999) <> NVL(src.CHECK_IN_WEATHER, -999.999) OR
            NVL(tgt.CHECK_IN_LATE, -999.999) <> NVL(src.CHECK_IN_LATE, -999.999) OR
            NVL(tgt.CHECK_IN_MISC_NON_TAX, -999.999) <> NVL(src.CHECK_IN_MISC_NON_TAX, -999.999) OR
            NVL(tgt.CHECK_IN_MISC_TAX, -999.999) <> NVL(src.CHECK_IN_MISC_TAX, -999.999) OR
            NVL(tgt.CHECK_IN_CLEANING, -999.999) <> NVL(src.CHECK_IN_CLEANING, -999.999) OR
            NVL(tgt.CHECK_IN_GALLONS, -999.999) <> NVL(src.CHECK_IN_GALLONS, -999.999) OR
            NVL(tgt.CHECK_IN_FUEL, -999.999) <> NVL(src.CHECK_IN_FUEL, -999.999) OR
            NVL(tgt.CHECK_IN_DIESEL_GALLONS, -999.999) <> NVL(src.CHECK_IN_DIESEL_GALLONS, -999.999) OR
            NVL(tgt.CHECK_IN_DIESEL, -999.999) <> NVL(src.CHECK_IN_DIESEL, -999.999) OR
            NVL(tgt.CHECK_IN_TIP, -999.999) <> NVL(src.CHECK_IN_TIP, -999.999) OR
            NVL(tgt.CHECK_IN_TAX_1, -999.999) <> NVL(src.CHECK_IN_TAX_1, -999.999) OR
            NVL(tgt.CHECK_IN_TAX_2, -999.999) <> NVL(src.CHECK_IN_TAX_2, -999.999) OR
            NVL(tgt.CHECK_IN_TOTAL, -999.999) <> NVL(src.CHECK_IN_TOTAL, -999.999) OR
            NVL(tgt.QUEUE_ADMIN_ID, -999) <> NVL(src.QUEUE_ADMIN_ID, -999) OR
            NVL(tgt.QUEUE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.QUEUE_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.ATTENDANT_QUEUE_ADMIN_ID, -999) <> NVL(src.ATTENDANT_QUEUE_ADMIN_ID, -999) OR
            NVL(tgt.ATTENDANT_WATER_ADMIN_ID, -999) <> NVL(src.ATTENDANT_WATER_ADMIN_ID, -999) OR
            NVL(tgt.BOAT_ASSIGNED, -999) <> NVL(src.BOAT_ASSIGNED, -999) OR
            NVL(tgt.ADDITIONAL_DRIVERS, -999) <> NVL(src.ADDITIONAL_DRIVERS, -999) OR
            NVL(tgt.ACCESSORIES_MIGRATED, -999) <> NVL(src.ACCESSORIES_MIGRATED, -999) OR
            NVL(tgt.PRICE_RULE_ID, -999) <> NVL(src.PRICE_RULE_ID, -999) OR
            NVL(tgt.PRICE_RULE_ORIGINAL_PRICE, -999.999) <> NVL(src.PRICE_RULE_ORIGINAL_PRICE, -999.999) OR
            NVL(tgt.PRICE_RULE_DYNAMIC_PRICE, -999.999) <> NVL(src.PRICE_RULE_DYNAMIC_PRICE, -999.999) OR
            NVL(tgt.PRICE_RULE_DIFFERENCE, -999.999) <> NVL(src.PRICE_RULE_DIFFERENCE, -999.999) OR
            NVL(tgt.EMERGENCY_NAME, '~NULL~') <> NVL(src.EMERGENCY_NAME, '~NULL~') OR
            NVL(tgt.EMERGENCY_PHONE, '~NULL~') <> NVL(src.EMERGENCY_PHONE, '~NULL~') OR
            NVL(tgt.DATE_OF_BIRTH, '~NULL~') <> NVL(src.DATE_OF_BIRTH, '~NULL~') OR
            NVL(tgt.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.UPDATED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.DELETED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.DELETED_AT, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, BOOKING_ID, STYLE_ID, BOAT_ID, TIME_ID, TIMEFRAME_ID, MAIN_BOAT, NUM_PASSENGERS, BOAT_DEPARTURE, BOAT_RETURN, STATUS_BOOKING, PRICE, PRICE_OVERRIDE, SIGNATURE_DATE, CHECK_OUT_DATE, CHECK_OUT_EQUIPMENT, CHECK_OUT_NOTES, CHECK_OUT_ENGINE_HOURS, CHECK_IN_DATE, CHECK_IN_EQUIPMENT, CHECK_IN_NOTES, CHECK_IN_ENGINE_HOURS, CHECK_IN_HOURS, CHECK_IN_DEPOSIT, CHECK_IN_WEATHER, CHECK_IN_LATE, CHECK_IN_MISC_NON_TAX, CHECK_IN_MISC_TAX, CHECK_IN_CLEANING, CHECK_IN_GALLONS, CHECK_IN_FUEL, CHECK_IN_DIESEL_GALLONS, CHECK_IN_DIESEL, CHECK_IN_TIP, CHECK_IN_TAX_1, CHECK_IN_TAX_2, CHECK_IN_TOTAL, QUEUE_ADMIN_ID, QUEUE_DATE, ATTENDANT_QUEUE_ADMIN_ID, ATTENDANT_WATER_ADMIN_ID, BOAT_ASSIGNED, ADDITIONAL_DRIVERS, ADDITIONAL_DRIVER_NAMES, ACCESSORIES_MIGRATED, PRICE_RULE_ID, PRICE_RULE_ORIGINAL_PRICE, PRICE_RULE_DYNAMIC_PRICE, PRICE_RULE_DIFFERENCE, EMERGENCY_NAME, EMERGENCY_PHONE, DATE_OF_BIRTH, CONTRACT_RETURN_PDF, CONTRACT_PDF, CREATED_AT, UPDATED_AT, DELETED_AT,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.BOOKING_ID, src.STYLE_ID, src.BOAT_ID, src.TIME_ID, src.TIMEFRAME_ID, src.MAIN_BOAT, src.NUM_PASSENGERS, src.BOAT_DEPARTURE, src.BOAT_RETURN, src.STATUS_BOOKING, src.PRICE, src.PRICE_OVERRIDE, src.SIGNATURE_DATE, src.CHECK_OUT_DATE, src.CHECK_OUT_EQUIPMENT, src.CHECK_OUT_NOTES, src.CHECK_OUT_ENGINE_HOURS, src.CHECK_IN_DATE, src.CHECK_IN_EQUIPMENT, src.CHECK_IN_NOTES, src.CHECK_IN_ENGINE_HOURS, src.CHECK_IN_HOURS, src.CHECK_IN_DEPOSIT, src.CHECK_IN_WEATHER, src.CHECK_IN_LATE, src.CHECK_IN_MISC_NON_TAX, src.CHECK_IN_MISC_TAX, src.CHECK_IN_CLEANING, src.CHECK_IN_GALLONS, src.CHECK_IN_FUEL, src.CHECK_IN_DIESEL_GALLONS, src.CHECK_IN_DIESEL, src.CHECK_IN_TIP, src.CHECK_IN_TAX_1, src.CHECK_IN_TAX_2, src.CHECK_IN_TOTAL, src.QUEUE_ADMIN_ID, src.QUEUE_DATE, src.ATTENDANT_QUEUE_ADMIN_ID, src.ATTENDANT_WATER_ADMIN_ID, src.BOAT_ASSIGNED, src.ADDITIONAL_DRIVERS, src.ADDITIONAL_DRIVER_NAMES, src.ACCESSORIES_MIGRATED, src.PRICE_RULE_ID, src.PRICE_RULE_ORIGINAL_PRICE, src.PRICE_RULE_DYNAMIC_PRICE, src.PRICE_RULE_DIFFERENCE, src.EMERGENCY_NAME, src.EMERGENCY_PHONE, src.DATE_OF_BIRTH, src.CONTRACT_RETURN_PDF, src.CONTRACT_PDF, src.CREATED_AT, src.UPDATED_AT, src.DELETED_AT,
            v_timestamp,
            v_timestamp
        );
    
    -- Count updated records
    SELECT COUNT(*) INTO v_updated
    FROM DW_STELLAR_BOOKING_BOATS
    WHERE DW_LAST_UPDATED = v_timestamp
    AND DW_LAST_UPDATED > DW_LAST_INSERTED;
    
    -- Count inserted records
    SELECT COUNT(*) INTO v_inserted
    FROM DW_STELLAR_BOOKING_BOATS
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_STELLAR_BOOKING_BOATS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_STELLAR_BOOKING_BOATS: ' || SQLERRM);
        RAISE;
END SP_MERGE_STELLAR_BOOKING_BOATS;
/
