
-- ============================================================================
-- Merge STG_MOLO_CONTACTS to DW_MOLO_CONTACTS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_CONTACTS
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    -- Store current timestamp for tracking
    v_timestamp := SYSTIMESTAMP;
    
    MERGE INTO DW_MOLO_CONTACTS tgt
    USING STG_MOLO_CONTACTS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.EMAILS = src.EMAILS,
            tgt.FIRST_NAME = src.FIRST_NAME,
            tgt.MIDDLE_NAME = src.MIDDLE_NAME,
            tgt.LAST_NAME = src.LAST_NAME,
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.NOTES = src.NOTES,
            tgt.RECORD_STATUS_ID = src.RECORD_STATUS_ID,
            tgt.IS_SUPPLIER = src.IS_SUPPLIER,
            tgt.IS_CUSTOMER = src.IS_CUSTOMER,
            tgt.XERO_ID = src.XERO_ID,
            tgt.COMPANY_CONTACT_NAME = src.COMPANY_CONTACT_NAME,
            tgt.CREATION_USER = src.CREATION_USER,
            tgt.CREATION_DATE_TIME = src.CREATION_DATE_TIME,
            tgt.CIM_ID = src.CIM_ID,
            tgt.MARINA_LOCATION1_ID = src.MARINA_LOCATION1_ID,
            tgt.QB_CUSTOMER_ID = src.QB_CUSTOMER_ID,
            tgt.STATEMENTS_PREFERENCE_ID = src.STATEMENTS_PREFERENCE_ID,
            tgt.HASH_ID = src.HASH_ID,
            tgt.MOLO_API_PARTNER_ID = src.MOLO_API_PARTNER_ID,
            tgt.TAX_EXEMPT_STATUS = src.TAX_EXEMPT_STATUS,
            tgt.AUTOMATIC_DISCOUNT_PERCENT = src.AUTOMATIC_DISCOUNT_PERCENT,
            tgt.COST_PLUS_DISCOUNT = src.COST_PLUS_DISCOUNT,
            tgt.LINKED_PARENT_CONTACT = src.LINKED_PARENT_CONTACT,
            tgt.CONTACT_AUTO_CHARGE_ID = src.CONTACT_AUTO_CHARGE_ID,
            tgt.LAST_EDITED_DATE_TIME = src.LAST_EDITED_DATE_TIME,
            tgt.LAST_EDITED_USER_ID = src.LAST_EDITED_USER_ID,
            tgt.LAST_EDITED_MOLO_API_PARTNER_ID = src.LAST_EDITED_MOLO_API_PARTNER_ID,
            tgt.STRIPE_CUSTOMER_ID = src.STRIPE_CUSTOMER_ID,
            tgt.ACCOUNT_LIMIT = src.ACCOUNT_LIMIT,
            tgt.FILESTACK_ID = src.FILESTACK_ID,
            tgt.SHOW_COMPANY_NAME_PRINTED = src.SHOW_COMPANY_NAME_PRINTED,
            tgt.BOOKING_MERGING_DONE = src.BOOKING_MERGING_DONE,
            tgt.DATE_OF_BIRTH = src.DATE_OF_BIRTH,
            tgt.IDS_CUSTOMER_ID = src.IDS_CUSTOMER_ID,
            tgt.DO_NOT_LAUNCH = src.DO_NOT_LAUNCH,
            tgt.DO_NOT_LAUNCH_REASON = src.DO_NOT_LAUNCH_REASON,
            tgt.DRIVER_LICENSE_ID = src.DRIVER_LICENSE_ID,
            tgt.QUICKBOOKS_ID = src.QUICKBOOKS_ID,
            tgt.QUICKBOOKS_NAME = src.QUICKBOOKS_NAME,
            tgt.QBO_VENDOR_ID = src.QBO_VENDOR_ID,
            tgt.SKIP_FOR_FINANCE_CHARGES = src.SKIP_FOR_FINANCE_CHARGES,
            tgt.MAIN_CONTACT_ID = src.MAIN_CONTACT_ID,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.EMAILS, '~NULL~') <> NVL(src.EMAILS, '~NULL~') OR
            NVL(tgt.FIRST_NAME, '~NULL~') <> NVL(src.FIRST_NAME, '~NULL~') OR
            NVL(tgt.MIDDLE_NAME, '~NULL~') <> NVL(src.MIDDLE_NAME, '~NULL~') OR
            NVL(tgt.LAST_NAME, '~NULL~') <> NVL(src.LAST_NAME, '~NULL~') OR
            NVL(tgt.MARINA_LOCATION_ID, -999) <> NVL(src.MARINA_LOCATION_ID, -999) OR
            NVL(tgt.NOTES, '~NULL~') <> NVL(src.NOTES, '~NULL~') OR
            NVL(tgt.RECORD_STATUS_ID, -999) <> NVL(src.RECORD_STATUS_ID, -999) OR
            NVL(tgt.IS_SUPPLIER, -999) <> NVL(src.IS_SUPPLIER, -999) OR
            NVL(tgt.IS_CUSTOMER, -999) <> NVL(src.IS_CUSTOMER, -999) OR
            NVL(tgt.XERO_ID, '~NULL~') <> NVL(src.XERO_ID, '~NULL~') OR
            NVL(tgt.COMPANY_CONTACT_NAME, '~NULL~') <> NVL(src.COMPANY_CONTACT_NAME, '~NULL~') OR
            NVL(tgt.CREATION_USER, '~NULL~') <> NVL(src.CREATION_USER, '~NULL~') OR
            NVL(tgt.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATION_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.CIM_ID, -999) <> NVL(src.CIM_ID, -999) OR
            NVL(tgt.MARINA_LOCATION1_ID, -999) <> NVL(src.MARINA_LOCATION1_ID, -999) OR
            NVL(tgt.QB_CUSTOMER_ID, -999) <> NVL(src.QB_CUSTOMER_ID, -999) OR
            NVL(tgt.STATEMENTS_PREFERENCE_ID, -999) <> NVL(src.STATEMENTS_PREFERENCE_ID, -999) OR
            NVL(tgt.HASH_ID, '~NULL~') <> NVL(src.HASH_ID, '~NULL~') OR
            NVL(tgt.MOLO_API_PARTNER_ID, -999) <> NVL(src.MOLO_API_PARTNER_ID, -999) OR
            NVL(tgt.TAX_EXEMPT_STATUS, -999) <> NVL(src.TAX_EXEMPT_STATUS, -999) OR
            NVL(tgt.AUTOMATIC_DISCOUNT_PERCENT, -999) <> NVL(src.AUTOMATIC_DISCOUNT_PERCENT, -999) OR
            NVL(tgt.COST_PLUS_DISCOUNT, -999.999) <> NVL(src.COST_PLUS_DISCOUNT, -999.999) OR
            NVL(tgt.LINKED_PARENT_CONTACT, -999) <> NVL(src.LINKED_PARENT_CONTACT, -999) OR
            NVL(tgt.CONTACT_AUTO_CHARGE_ID, -999) <> NVL(src.CONTACT_AUTO_CHARGE_ID, -999) OR
            NVL(tgt.LAST_EDITED_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.LAST_EDITED_DATE_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.LAST_EDITED_USER_ID, '~NULL~') <> NVL(src.LAST_EDITED_USER_ID, '~NULL~') OR
            NVL(tgt.LAST_EDITED_MOLO_API_PARTNER_ID, -999) <> NVL(src.LAST_EDITED_MOLO_API_PARTNER_ID, -999) OR
            NVL(tgt.STRIPE_CUSTOMER_ID, -999) <> NVL(src.STRIPE_CUSTOMER_ID, -999) OR
            NVL(tgt.ACCOUNT_LIMIT, -999.999) <> NVL(src.ACCOUNT_LIMIT, -999.999) OR
            NVL(tgt.FILESTACK_ID, -999) <> NVL(src.FILESTACK_ID, -999) OR
            NVL(tgt.SHOW_COMPANY_NAME_PRINTED, -999) <> NVL(src.SHOW_COMPANY_NAME_PRINTED, -999) OR
            NVL(tgt.BOOKING_MERGING_DONE, -999) <> NVL(src.BOOKING_MERGING_DONE, -999) OR
            NVL(tgt.DATE_OF_BIRTH, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.DATE_OF_BIRTH, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.IDS_CUSTOMER_ID, '~NULL~') <> NVL(src.IDS_CUSTOMER_ID, '~NULL~') OR
            NVL(tgt.DO_NOT_LAUNCH, -999) <> NVL(src.DO_NOT_LAUNCH, -999) OR
            NVL(tgt.DO_NOT_LAUNCH_REASON, '~NULL~') <> NVL(src.DO_NOT_LAUNCH_REASON, '~NULL~') OR
            NVL(tgt.DRIVER_LICENSE_ID, '~NULL~') <> NVL(src.DRIVER_LICENSE_ID, '~NULL~') OR
            NVL(tgt.QUICKBOOKS_ID, '~NULL~') <> NVL(src.QUICKBOOKS_ID, '~NULL~') OR
            NVL(tgt.QUICKBOOKS_NAME, '~NULL~') <> NVL(src.QUICKBOOKS_NAME, '~NULL~') OR
            NVL(tgt.QBO_VENDOR_ID, '~NULL~') <> NVL(src.QBO_VENDOR_ID, '~NULL~') OR
            NVL(tgt.SKIP_FOR_FINANCE_CHARGES, -999) <> NVL(src.SKIP_FOR_FINANCE_CHARGES, -999) OR
            NVL(tgt.MAIN_CONTACT_ID, -999) <> NVL(src.MAIN_CONTACT_ID, -999)
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, EMAILS, FIRST_NAME, MIDDLE_NAME, LAST_NAME, MARINA_LOCATION_ID, NOTES, RECORD_STATUS_ID, IS_SUPPLIER, IS_CUSTOMER, XERO_ID, COMPANY_CONTACT_NAME, CREATION_USER, CREATION_DATE_TIME, CIM_ID, MARINA_LOCATION1_ID, QB_CUSTOMER_ID, STATEMENTS_PREFERENCE_ID, HASH_ID, MOLO_API_PARTNER_ID, TAX_EXEMPT_STATUS, AUTOMATIC_DISCOUNT_PERCENT, COST_PLUS_DISCOUNT, LINKED_PARENT_CONTACT, CONTACT_AUTO_CHARGE_ID, LAST_EDITED_DATE_TIME, LAST_EDITED_USER_ID, LAST_EDITED_MOLO_API_PARTNER_ID, STRIPE_CUSTOMER_ID, ACCOUNT_LIMIT, FILESTACK_ID, SHOW_COMPANY_NAME_PRINTED, BOOKING_MERGING_DONE, DATE_OF_BIRTH, IDS_CUSTOMER_ID, DO_NOT_LAUNCH, DO_NOT_LAUNCH_REASON, DRIVER_LICENSE_ID, QUICKBOOKS_ID, QUICKBOOKS_NAME, QBO_VENDOR_ID, SKIP_FOR_FINANCE_CHARGES, MAIN_CONTACT_ID,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.EMAILS, src.FIRST_NAME, src.MIDDLE_NAME, src.LAST_NAME, src.MARINA_LOCATION_ID, src.NOTES, src.RECORD_STATUS_ID, src.IS_SUPPLIER, src.IS_CUSTOMER, src.XERO_ID, src.COMPANY_CONTACT_NAME, src.CREATION_USER, src.CREATION_DATE_TIME, src.CIM_ID, src.MARINA_LOCATION1_ID, src.QB_CUSTOMER_ID, src.STATEMENTS_PREFERENCE_ID, src.HASH_ID, src.MOLO_API_PARTNER_ID, src.TAX_EXEMPT_STATUS, src.AUTOMATIC_DISCOUNT_PERCENT, src.COST_PLUS_DISCOUNT, src.LINKED_PARENT_CONTACT, src.CONTACT_AUTO_CHARGE_ID, src.LAST_EDITED_DATE_TIME, src.LAST_EDITED_USER_ID, src.LAST_EDITED_MOLO_API_PARTNER_ID, src.STRIPE_CUSTOMER_ID, src.ACCOUNT_LIMIT, src.FILESTACK_ID, src.SHOW_COMPANY_NAME_PRINTED, src.BOOKING_MERGING_DONE, src.DATE_OF_BIRTH, src.IDS_CUSTOMER_ID, src.DO_NOT_LAUNCH, src.DO_NOT_LAUNCH_REASON, src.DRIVER_LICENSE_ID, src.QUICKBOOKS_ID, src.QUICKBOOKS_NAME, src.QBO_VENDOR_ID, src.SKIP_FOR_FINANCE_CHARGES, src.MAIN_CONTACT_ID,
            v_timestamp,
            v_timestamp
        );
    
    -- Count records that were updated (DW_LAST_UPDATED = current timestamp and > DW_LAST_INSERTED)
    SELECT COUNT(*)
    INTO v_updated
    FROM DW_MOLO_CONTACTS
    WHERE DW_LAST_UPDATED = v_timestamp
    AND DW_LAST_UPDATED > DW_LAST_INSERTED;
    
    -- Count records that were inserted (DW_LAST_INSERTED = current timestamp)
    SELECT COUNT(*)
    INTO v_inserted
    FROM DW_MOLO_CONTACTS
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_CONTACTS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_CONTACTS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_CONTACTS;
/
