
-- ============================================================================
-- Merge STG_MOLO_TRANSACTIONS to DW_MOLO_TRANSACTIONS
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_MERGE_MOLO_TRANSACTIONS
IS
    v_inserted NUMBER := 0;
    v_updated NUMBER := 0;
    v_timestamp TIMESTAMP := SYSTIMESTAMP;
BEGIN
    v_timestamp := SYSTIMESTAMP;
    
    MERGE INTO DW_MOLO_TRANSACTIONS tgt
    USING STG_MOLO_TRANSACTIONS src
    ON (tgt.ID = src.ID)
    WHEN MATCHED THEN
        UPDATE SET
            tgt.MARINA_LOCATION_ID = src.MARINA_LOCATION_ID,
            tgt.CREATION_TIME = src.CREATION_TIME,
            tgt.INVOICE_ID = src.INVOICE_ID,
            tgt.TRANSACTION_TYPE_ID = src.TRANSACTION_TYPE_ID,
            tgt.TRANSACTION_METHOD_ID = src.TRANSACTION_METHOD_ID,
            tgt.VALUE_FIELD = src.VALUE_FIELD,
            tgt.IS_REFUNDED = src.IS_REFUNDED,
            tgt.CUSTOMER_IP_ADDRESS = src.CUSTOMER_IP_ADDRESS,
            tgt.CUSTOMER_DEVICE = src.CUSTOMER_DEVICE,
            tgt.REFUND_REASON = src.REFUND_REASON,
            tgt.AUX = src.AUX,
            tgt.CHECK_NUMBER = src.CHECK_NUMBER,
            tgt.CC_TYPE = src.CC_TYPE,
            tgt.INVOICE_ITEM_ID = src.INVOICE_ITEM_ID,
            tgt.SENT_TO_XERO = src.SENT_TO_XERO,
            tgt.OVERPAYMENT_ID = src.OVERPAYMENT_ID,
            tgt.PAYMENT_COLLECTED_OFFLINE = src.PAYMENT_COLLECTED_OFFLINE,
            tgt.PART_OF_OVERPAYMENT = src.PART_OF_OVERPAYMENT,
            tgt.PREPAYMENT_ID = src.PREPAYMENT_ID,
            tgt.ACCOUNT_TRANSACTION_TRANSACTION_ID = src.ACCOUNT_TRANSACTION_TRANSACTION_ID,
            tgt.PAYMENT_ID = src.PAYMENT_ID,
            tgt.CREATION_DATE = src.CREATION_DATE,
            tgt.ASPNET_USER_ID = src.ASPNET_USER_ID,
            tgt.HASH_ID = src.HASH_ID,
            tgt.CUSTOM_TRANSACTION_METHODS_ID = src.CUSTOM_TRANSACTION_METHODS_ID,
            tgt.REFERENCE = src.REFERENCE,
            tgt.IS_VOID = src.IS_VOID,
            tgt.AMOUNT_REFUNDED = src.AMOUNT_REFUNDED,
            tgt.STRIPE_TRANSACTION_DATA_ID = src.STRIPE_TRANSACTION_DATA_ID,
            tgt.PAYMENT_INTENT_ID = src.PAYMENT_INTENT_ID,
            tgt.SENT_TO_PAYOUT = src.SENT_TO_PAYOUT,
            tgt.STRIPE_AUTHORIZATIONS_ID = src.STRIPE_AUTHORIZATIONS_ID,
            tgt.STRIPE_RESPONSE_ID = src.STRIPE_RESPONSE_ID,
            tgt.STRIPE_READER_SERIAL_NUMBER = src.STRIPE_READER_SERIAL_NUMBER,
            tgt.STRIPE_TERMINAL_ID = src.STRIPE_TERMINAL_ID,
            tgt.CREATED_ON_MOBILE = src.CREATED_ON_MOBILE,
            tgt.ONLINE_PERCENT_FEE = src.ONLINE_PERCENT_FEE,
            tgt.ONLINE_FEE_AMOUNT = src.ONLINE_FEE_AMOUNT,
            tgt.SCHEDULED_FOR_ONLINE_FEE_CRON = src.SCHEDULED_FOR_ONLINE_FEE_CRON,
            tgt.ONLINE_PAYMENT_FEE_ID = src.ONLINE_PAYMENT_FEE_ID,
            tgt.BANK_NAME = src.BANK_NAME,
            tgt.LAST4 = src.LAST4,
            tgt.STRIPE_BANK_ACCOUNT_ID = src.STRIPE_BANK_ACCOUNT_ID,
            tgt.STRIPE_BATCH_ID = src.STRIPE_BATCH_ID,
            tgt.ROUTING_NUMBER = src.ROUTING_NUMBER,
            tgt.FULLY_REFUNDED = src.FULLY_REFUNDED,
            tgt.LAST_UPDATED = src.LAST_UPDATED,
            tgt.PAYMENT_SOURCE = src.PAYMENT_SOURCE,
            tgt.DW_LAST_UPDATED = v_timestamp
        WHERE (
            NVL(tgt.ID, -999) <> NVL(src.ID, -999) OR
            NVL(tgt.MARINA_LOCATION_ID, -999) <> NVL(src.MARINA_LOCATION_ID, -999) OR
            NVL(tgt.CREATION_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATION_TIME, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.INVOICE_ID, -999) <> NVL(src.INVOICE_ID, -999) OR
            NVL(tgt.TRANSACTION_TYPE_ID, -999) <> NVL(src.TRANSACTION_TYPE_ID, -999) OR
            NVL(tgt.TRANSACTION_METHOD_ID, -999) <> NVL(src.TRANSACTION_METHOD_ID, -999) OR
            NVL(tgt.VALUE_FIELD, -999.999) <> NVL(src.VALUE_FIELD, -999.999) OR
            NVL(tgt.IS_REFUNDED, -999) <> NVL(src.IS_REFUNDED, -999) OR
            NVL(tgt.CUSTOMER_IP_ADDRESS, '~NULL~') <> NVL(src.CUSTOMER_IP_ADDRESS, '~NULL~') OR
            NVL(tgt.CUSTOMER_DEVICE, '~NULL~') <> NVL(src.CUSTOMER_DEVICE, '~NULL~') OR
            NVL(tgt.REFUND_REASON, '~NULL~') <> NVL(src.REFUND_REASON, '~NULL~') OR
            NVL(tgt.AUX, '~NULL~') <> NVL(src.AUX, '~NULL~') OR
            NVL(tgt.CHECK_NUMBER, '~NULL~') <> NVL(src.CHECK_NUMBER, '~NULL~') OR
            NVL(tgt.CC_TYPE, '~NULL~') <> NVL(src.CC_TYPE, '~NULL~') OR
            NVL(tgt.INVOICE_ITEM_ID, -999) <> NVL(src.INVOICE_ITEM_ID, -999) OR
            NVL(tgt.SENT_TO_XERO, -999) <> NVL(src.SENT_TO_XERO, -999) OR
            NVL(tgt.OVERPAYMENT_ID, '~NULL~') <> NVL(src.OVERPAYMENT_ID, '~NULL~') OR
            NVL(tgt.PAYMENT_COLLECTED_OFFLINE, -999) <> NVL(src.PAYMENT_COLLECTED_OFFLINE, -999) OR
            NVL(tgt.PART_OF_OVERPAYMENT, -999) <> NVL(src.PART_OF_OVERPAYMENT, -999) OR
            NVL(tgt.PREPAYMENT_ID, '~NULL~') <> NVL(src.PREPAYMENT_ID, '~NULL~') OR
            NVL(tgt.ACCOUNT_TRANSACTION_TRANSACTION_ID, -999) <> NVL(src.ACCOUNT_TRANSACTION_TRANSACTION_ID, -999) OR
            NVL(tgt.PAYMENT_ID, -999) <> NVL(src.PAYMENT_ID, -999) OR
            NVL(tgt.CREATION_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.CREATION_DATE, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.ASPNET_USER_ID, '~NULL~') <> NVL(src.ASPNET_USER_ID, '~NULL~') OR
            NVL(tgt.HASH_ID, '~NULL~') <> NVL(src.HASH_ID, '~NULL~') OR
            NVL(tgt.CUSTOM_TRANSACTION_METHODS_ID, -999) <> NVL(src.CUSTOM_TRANSACTION_METHODS_ID, -999) OR
            NVL(tgt.REFERENCE, '~NULL~') <> NVL(src.REFERENCE, '~NULL~') OR
            NVL(tgt.IS_VOID, -999) <> NVL(src.IS_VOID, -999) OR
            NVL(tgt.AMOUNT_REFUNDED, -999.999) <> NVL(src.AMOUNT_REFUNDED, -999.999) OR
            NVL(tgt.STRIPE_TRANSACTION_DATA_ID, -999) <> NVL(src.STRIPE_TRANSACTION_DATA_ID, -999) OR
            NVL(tgt.PAYMENT_INTENT_ID, '~NULL~') <> NVL(src.PAYMENT_INTENT_ID, '~NULL~') OR
            NVL(tgt.SENT_TO_PAYOUT, -999) <> NVL(src.SENT_TO_PAYOUT, -999) OR
            NVL(tgt.STRIPE_AUTHORIZATIONS_ID, -999) <> NVL(src.STRIPE_AUTHORIZATIONS_ID, -999) OR
            NVL(tgt.STRIPE_RESPONSE_ID, -999) <> NVL(src.STRIPE_RESPONSE_ID, -999) OR
            NVL(tgt.STRIPE_READER_SERIAL_NUMBER, '~NULL~') <> NVL(src.STRIPE_READER_SERIAL_NUMBER, '~NULL~') OR
            NVL(tgt.STRIPE_TERMINAL_ID, '~NULL~') <> NVL(src.STRIPE_TERMINAL_ID, '~NULL~') OR
            NVL(tgt.CREATED_ON_MOBILE, -999) <> NVL(src.CREATED_ON_MOBILE, -999) OR
            NVL(tgt.ONLINE_PERCENT_FEE, -999.999) <> NVL(src.ONLINE_PERCENT_FEE, -999.999) OR
            NVL(tgt.ONLINE_FEE_AMOUNT, -999.999) <> NVL(src.ONLINE_FEE_AMOUNT, -999.999) OR
            NVL(tgt.SCHEDULED_FOR_ONLINE_FEE_CRON, -999) <> NVL(src.SCHEDULED_FOR_ONLINE_FEE_CRON, -999) OR
            NVL(tgt.ONLINE_PAYMENT_FEE_ID, -999) <> NVL(src.ONLINE_PAYMENT_FEE_ID, -999) OR
            NVL(tgt.BANK_NAME, '~NULL~') <> NVL(src.BANK_NAME, '~NULL~') OR
            NVL(tgt.LAST4, '~NULL~') <> NVL(src.LAST4, '~NULL~') OR
            NVL(tgt.STRIPE_BANK_ACCOUNT_ID, -999) <> NVL(src.STRIPE_BANK_ACCOUNT_ID, -999) OR
            NVL(tgt.STRIPE_BATCH_ID, -999) <> NVL(src.STRIPE_BATCH_ID, -999) OR
            NVL(tgt.ROUTING_NUMBER, '~NULL~') <> NVL(src.ROUTING_NUMBER, '~NULL~') OR
            NVL(tgt.FULLY_REFUNDED, -999) <> NVL(src.FULLY_REFUNDED, -999) OR
            NVL(tgt.LAST_UPDATED, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) <> NVL(src.LAST_UPDATED, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) OR
            NVL(tgt.PAYMENT_SOURCE, '~NULL~') <> NVL(src.PAYMENT_SOURCE, '~NULL~')
        )
    WHEN NOT MATCHED THEN
        INSERT (
            ID, MARINA_LOCATION_ID, CREATION_TIME, INVOICE_ID, TRANSACTION_TYPE_ID, TRANSACTION_METHOD_ID, VALUE_FIELD, IS_REFUNDED, CUSTOMER_IP_ADDRESS, CUSTOMER_DEVICE, REFUND_REASON, AUX, CHECK_NUMBER, CC_TYPE, INVOICE_ITEM_ID, SENT_TO_XERO, OVERPAYMENT_ID, PAYMENT_COLLECTED_OFFLINE, PART_OF_OVERPAYMENT, PREPAYMENT_ID, ACCOUNT_TRANSACTION_TRANSACTION_ID, PAYMENT_ID, CREATION_DATE, ASPNET_USER_ID, HASH_ID, CUSTOM_TRANSACTION_METHODS_ID, REFERENCE, IS_VOID, AMOUNT_REFUNDED, STRIPE_TRANSACTION_DATA_ID, PAYMENT_INTENT_ID, SENT_TO_PAYOUT, STRIPE_AUTHORIZATIONS_ID, STRIPE_RESPONSE_ID, STRIPE_READER_SERIAL_NUMBER, STRIPE_TERMINAL_ID, CREATED_ON_MOBILE, ONLINE_PERCENT_FEE, ONLINE_FEE_AMOUNT, SCHEDULED_FOR_ONLINE_FEE_CRON, ONLINE_PAYMENT_FEE_ID, BANK_NAME, LAST4, STRIPE_BANK_ACCOUNT_ID, STRIPE_BATCH_ID, ROUTING_NUMBER, FULLY_REFUNDED, LAST_UPDATED, PAYMENT_SOURCE,
            DW_LAST_INSERTED,
            DW_LAST_UPDATED
        )
        VALUES (
            src.ID, src.MARINA_LOCATION_ID, src.CREATION_TIME, src.INVOICE_ID, src.TRANSACTION_TYPE_ID, src.TRANSACTION_METHOD_ID, src.VALUE_FIELD, src.IS_REFUNDED, src.CUSTOMER_IP_ADDRESS, src.CUSTOMER_DEVICE, src.REFUND_REASON, src.AUX, src.CHECK_NUMBER, src.CC_TYPE, src.INVOICE_ITEM_ID, src.SENT_TO_XERO, src.OVERPAYMENT_ID, src.PAYMENT_COLLECTED_OFFLINE, src.PART_OF_OVERPAYMENT, src.PREPAYMENT_ID, src.ACCOUNT_TRANSACTION_TRANSACTION_ID, src.PAYMENT_ID, src.CREATION_DATE, src.ASPNET_USER_ID, src.HASH_ID, src.CUSTOM_TRANSACTION_METHODS_ID, src.REFERENCE, src.IS_VOID, src.AMOUNT_REFUNDED, src.STRIPE_TRANSACTION_DATA_ID, src.PAYMENT_INTENT_ID, src.SENT_TO_PAYOUT, src.STRIPE_AUTHORIZATIONS_ID, src.STRIPE_RESPONSE_ID, src.STRIPE_READER_SERIAL_NUMBER, src.STRIPE_TERMINAL_ID, src.CREATED_ON_MOBILE, src.ONLINE_PERCENT_FEE, src.ONLINE_FEE_AMOUNT, src.SCHEDULED_FOR_ONLINE_FEE_CRON, src.ONLINE_PAYMENT_FEE_ID, src.BANK_NAME, src.LAST4, src.STRIPE_BANK_ACCOUNT_ID, src.STRIPE_BATCH_ID, src.ROUTING_NUMBER, src.FULLY_REFUNDED, src.LAST_UPDATED, src.PAYMENT_SOURCE,
            v_timestamp,
            v_timestamp
        );
    
    -- Count updated records
    SELECT COUNT(*) INTO v_updated
    FROM DW_MOLO_TRANSACTIONS
    WHERE DW_LAST_UPDATED = v_timestamp
    AND DW_LAST_UPDATED > DW_LAST_INSERTED;
    
    -- Count inserted records
    SELECT COUNT(*) INTO v_inserted
    FROM DW_MOLO_TRANSACTIONS
    WHERE DW_LAST_INSERTED = v_timestamp;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('DW_MOLO_TRANSACTIONS: ' || v_inserted || ' inserted, ' || v_updated || ' updated');
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error in SP_MERGE_MOLO_TRANSACTIONS: ' || SQLERRM);
        RAISE;
END SP_MERGE_MOLO_TRANSACTIONS;
/
